#!/bin/bash
# MeshVPN Exit Node Bootstrap Script
set -e

# Variables from Terraform
ENVIRONMENT="${environment}"
DYNAMODB_TABLE="${dynamodb_table}"
S3_BUCKET="${s3_bucket}"
VPN_PORT="${vpn_port}"
REGION="${region}"

# Logging
exec > >(tee /var/log/meshvpn-init.log|logger -t meshvpn-init -s 2>/dev/console) 2>&1

echo "Starting MeshVPN exit node setup..."
echo "Environment: $ENVIRONMENT"
echo "Region: $REGION"

# Update system
dnf update -y

# Install required packages
dnf install -y \
    gcc \
    make \
    git \
    curl \
    wget \
    jq \
    htop \
    iptables-services \
    amazon-cloudwatch-agent

# Enable IP forwarding
cat > /etc/sysctl.d/99-meshvpn.conf << EOF
net.ipv4.ip_forward = 1
net.ipv4.conf.all.forwarding = 1
net.ipv6.conf.all.forwarding = 1
net.core.rmem_max = 26214400
net.core.wmem_max = 26214400
net.core.rmem_default = 1048576
net.core.wmem_default = 1048576
net.ipv4.udp_rmem_min = 8192
net.ipv4.udp_wmem_min = 8192
EOF
sysctl --system

# Configure iptables for NAT
# Get the primary network interface
PRIMARY_IF=$(ip route | grep default | awk '{print $5}' | head -1)

cat > /etc/sysconfig/iptables << EOF
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A POSTROUTING -o $PRIMARY_IF -j MASQUERADE
COMMIT
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -i lo -j ACCEPT
-A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
-A INPUT -p udp --dport $VPN_PORT -j ACCEPT
-A INPUT -p tcp --dport 22 -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT
-A FORWARD -i meshvpn+ -j ACCEPT
COMMIT
EOF

systemctl enable iptables
systemctl start iptables

# Install Rust (if building from source)
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
source $HOME/.cargo/env

# Create meshvpn user
useradd -r -s /sbin/nologin meshvpn || true

# Create directories
mkdir -p /etc/meshvpn
mkdir -p /var/lib/meshvpn
mkdir -p /var/log/meshvpn
chown -R meshvpn:meshvpn /var/lib/meshvpn /var/log/meshvpn

# Create configuration file
cat > /etc/meshvpn/exit.toml << EOF
# MeshVPN Exit Node Configuration
# Auto-generated by Terraform

[general]
environment = "$ENVIRONMENT"
log_level = "info"

[network]
listen_port = $VPN_PORT
outbound_interface = "$PRIMARY_IF"
enable_ipv6 = false

[aws]
region = "$REGION"
dynamodb_table = "$DYNAMODB_TABLE"
s3_bucket = "$S3_BUCKET"

[sync]
interval_secs = 30
heartbeat_secs = 10

[limits]
max_connections = 1000
bandwidth_limit_mbps = 100

[logging]
enable_connection_logging = true
log_retention_days = 7
compress_logs = true
EOF

chown meshvpn:meshvpn /etc/meshvpn/exit.toml
chmod 600 /etc/meshvpn/exit.toml

# Create systemd service file
cat > /etc/systemd/system/meshvpn-exit.service << 'EOF'
[Unit]
Description=MeshVPN Exit Node
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=meshvpn
Group=meshvpn
ExecStart=/usr/local/bin/meshvpn-exit start --config /etc/meshvpn/exit.toml
ExecReload=/bin/kill -HUP $MAINPID
Restart=always
RestartSec=5
LimitNOFILE=65535
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_RAW CAP_NET_BIND_SERVICE

# Security hardening
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
PrivateTmp=true
ReadWritePaths=/var/lib/meshvpn /var/log/meshvpn

[Install]
WantedBy=multi-user.target
EOF

# Configure CloudWatch agent
cat > /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json << EOF
{
  "agent": {
    "metrics_collection_interval": 60,
    "run_as_user": "root"
  },
  "logs": {
    "logs_collected": {
      "files": {
        "collect_list": [
          {
            "file_path": "/var/log/meshvpn/*.log",
            "log_group_name": "/meshvpn/exit-nodes/$ENVIRONMENT",
            "log_stream_name": "{instance_id}",
            "timestamp_format": "%Y-%m-%dT%H:%M:%S"
          },
          {
            "file_path": "/var/log/meshvpn-init.log",
            "log_group_name": "/meshvpn/exit-nodes/$ENVIRONMENT",
            "log_stream_name": "{instance_id}/init"
          }
        ]
      }
    }
  },
  "metrics": {
    "namespace": "MeshVPN",
    "metrics_collected": {
      "cpu": {
        "measurement": ["cpu_usage_idle", "cpu_usage_user", "cpu_usage_system"],
        "metrics_collection_interval": 60
      },
      "mem": {
        "measurement": ["mem_used_percent"],
        "metrics_collection_interval": 60
      },
      "net": {
        "measurement": ["bytes_sent", "bytes_recv", "packets_sent", "packets_recv"],
        "metrics_collection_interval": 60
      },
      "netstat": {
        "measurement": ["tcp_established", "udp_socket"],
        "metrics_collection_interval": 60
      }
    },
    "append_dimensions": {
      "InstanceId": "\${aws:InstanceId}",
      "Region": "$REGION",
      "Environment": "$ENVIRONMENT"
    }
  }
}
EOF

# Start CloudWatch agent
/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl \
    -a fetch-config \
    -m ec2 \
    -s \
    -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json

# Download MeshVPN binary (placeholder - would be replaced with actual download)
# For now, we'll just create a placeholder
echo "#!/bin/bash" > /usr/local/bin/meshvpn-exit
echo "echo 'MeshVPN Exit Node - Binary not yet deployed'" >> /usr/local/bin/meshvpn-exit
echo "exec sleep infinity" >> /usr/local/bin/meshvpn-exit
chmod +x /usr/local/bin/meshvpn-exit

# Enable and start service
systemctl daemon-reload
systemctl enable meshvpn-exit.service

# Don't start yet - wait for binary deployment
# systemctl start meshvpn-exit.service

# Signal setup complete
echo "MeshVPN exit node setup complete!"
echo "Instance ID: $(curl -s http://169.254.169.254/latest/meta-data/instance-id)"
echo "Public IP: $(curl -s http://169.254.169.254/latest/meta-data/public-ipv4 || echo 'N/A')"
echo "Private IP: $(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)"

# Create setup complete marker
touch /var/lib/meshvpn/.setup-complete
